context:
  name: polars-strsim
  version: "0.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/60/9d/d0b51d3991fc2ff0f1d2c6d0c6eb03a1ad8afeb5a35632ec2f6066194a5a/${{ name|replace("-","_") }}-${{ version }}.tar.gz
  sha256: 20871a8743ac3ab1326fa7f5d56e375b022c9cd6c5f8b6c51d5634a5907e7884

build:
  script:
    content:
      - echo $RUST_BACKTRACE
      - echo $TARGET
      - python -m pip install . -vv
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    env:
      RUST_BACKTRACE: "1"
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7.1,<2.0
    - pip
  run:
    - python
    - polars >1.2,<2.0
  
tests:
  - python:
      imports:
        - polars_strsim
      pip_check: true

about:
  homepage: https://github.com/foxcroftjn/polars-strsim
  summary: 'Polars extension for string similarity'
  description: |
    This package provides python bindings to compute various string similarity measures directly on a polars dataframe. All string similarity measures are implemented in rust and computed in parallel. The similarity measures that have been implemented are:
    Levenshtein
    Jaro
    Jaro-Winkler
    Jaccard
    Sørensen-Dice
    Each similarity measure returns a value normalized between 0.0 and 1.0 (inclusive), where 0.0 indicates the inputs are maximally different and 1.0 means the strings are maximally similar.
  license: MIT
  license_file: 
    - LICENSE
    - tHIRDPARTY.yml
  repository: https://github.com/foxcroftjn/polars-strsim

extra:
  recipe-maintainers:
    - EllaBootQC
