context:
  name: prince
  version: "0.15.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:

  url: https://files.pythonhosted.org/packages/24/2d/445c241764dc5602c955d6a9b00f00953ade0ca1ce8db143d053b818e932/${{ name }}-${{ version }}.tar.gz
  sha256: c4508347fa5433c50e8e5ef9bed63a25d8e568f4bfea16457097b7a64404bc19

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python <4.0,>=3.10
    - poetry-core >=1.0.0
    - pip
    - setuptools
  run:
    - python <4.0,>=3.10
    - scikit-learn >=1.5.1
    - pandas >=2.2.0
    - altair >=5.0.0

tests:
  - python:
      imports:
      - prince
      pip_check: true

about:
  homepage: https://github.com/MaxHalford/prince
  summary: 'A Python library for multivariate exploratory data analysis.'
  description: |
    Prince is a Python library for multivariate exploratory data analysis in Python. It includes a variety of methods for summarizing tabular data, including principal component analysis (PCA) and correspondence analysis (CA). Prince provides efficient implementations, using a scikit-learn API.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/MaxHalford/prince

extra:
  recipe-maintainers:
    - EllaBootQC
