context:
  name: polars_strsim
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/cd/0a/2f7dac45cfebc9372faabd183f52f05a7b5349722666f492056d64bc8e1f/${{ name }}-${{ version }}.tar.gz 
  sha256: 3e92bc81c933867e3e812a7000a51bc830d78377e079e0fc98bb26ad022879e3

build:
    # - cargo install --locked --bins --root {{ PREFIX }} --path .  # [unix]
    # - cargo install --locked --bins --root %PREFIX% --path .  # [win]
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    # - ${{ compiler('c') }}
    # - ${{ stdlib("c") }}  # If you need any compiler, add the C standard library ("stdlib") too
    # - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
    # - setuptools
  run:
    - python
    - polars # =0.43.1
    - pyo3 # =0.22.3
    - pyo3-polars =0.17.0
    - serde =1
    - rayon =1.10.0
    - jemallocator =0.5.4
  
tests:
  - python:
      imports:
        - polars_strsim
      pip_check: true

about:
  homepage: https://github.com/foxcroftjn/polars-strsim
  summary: 'Polars extension for string similarity'
  description: |
    This package provides python bindings to compute various string similarity measures directly on a polars dataframe. All string similarity measures are implemented in rust and computed in parallel. The similarity measures that have been implemented are:
    Levenshtein
    Jaro
    Jaro-Winkler
    Jaccard
    Sørensen-Dice
    Each similarity measure returns a value normalized between 0.0 and 1.0 (inclusive), where 0.0 indicates the inputs are maximally different and 1.0 means the strings are maximally similar.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/foxcroftjn/polars-strsim

extra:
  recipe-maintainers:
    - EllaBootQC
