context:
  name: mlflow-export-import
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mlflow/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 336bd0fe3a16ac2198774f89d2642df5d103d306a5a6d3b48f3eed90dbddf9c3

build:
  script: python -m pip install . -vv
  noarch: python
  number: 0
  python:
    entry_points:
      - export-all = mlflow_export_import.bulk.export_all:main
      - import-all = mlflow_export_import.bulk.import_models:main
      - export-models = mlflow_export_import.bulk.export_models:main
      - import-models = mlflow_export_import.bulk.import_models:main
      - export-run = mlflow_export_import.run.export_run:main
      - import-run = mlflow_export_import.run.import_run:main
      - export-experiment = mlflow_export_import.experiment.export_experiment:main
      - import-experiment = mlflow_export_import.experiment.import_experiment:main
      - export-experiments = mlflow_export_import.bulk.export_experiments:main
      - import-experiments = mlflow_export_import.bulk.import_experiments:main 
      - export-model = mlflow_export_import.model.export_model:main
      - import-model = mlflow_export_import.model.import_model:main
      - export-model-version = mlflow_export_import.model_version.export_model_version:main
      - import-model-version = mlflow_export_import.model_version.import_model_version:main
      - download-notebook = mlflow_export_import.notebook.download_notebook:main
      - copy-model-version = mlflow_export_import.copy.copy_model_version:main
      - copy-run = mlflow_export_import.copy.copy_run:main
      - get-model-signature = mlflow_export_import.tools.get_model_signature:main
      - set-model-signature = mlflow_export_import.tools.set_model_signature:main
      - list-model-versions-without-sigantures = mlflow_export_import.tools.list_model_versions_without_signatures:main
      - http-client = mlflow_export_import.client.http_client:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - mlflow >=2.9.2
  run:
    - python >=3.8
    - mlflow
    - databricks-cli ==0.18.0
    - pandas >=1.5.2
    - tabulate ==0.9.0
    - wheel
    - pytest
    - pytest-html >=3.2.0
    - shortuuid >=1.0.11

tests:
  - python:
      imports:
        - mlflow_export_import
      pip_check: true

about:
  homepage:  https://github.com/mlflow/mlflow-export-import
  summary: 'Tools to copy MLflow objects'
  description: |
    The MLflow Export Import package provides tools to copy MLflow objects (runs, experiments or registered models) from one MLflow tracking server (Databricks workspace) to another. Using the MLflow REST API, the tools export MLflow objects to an intermediate directory and then import them into the target tracking server.
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/mlflow/mlflow-export-import

extra:
  recipe-maintainers:
    - EllaBootQC
